name: apt 源修改
on:
  workflow_dispatch:
jobs:
  ext:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: 移动文件
        run: sudo cp /etc/apt/sources.list sources.list
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: sources.list
          path: sources.list
